### ISSUE TITLE
[Bug]: Changing shortcut with Shift modifier incorrectly assigns shortcut.

### ISSUE THREAD

**Issue by teropentis64** [mikekazakov/nimble-commander#393]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

Version 1.6.1 (4088), MacOS 15.0

### Distribution Type

Downloaded directly from the website (including Brew)

### Expected Result

Key shortcut assigned to Shift-1

### Actual Result

Key shortcut assigned to Shift-@

### Steps to reproduce

1. Go to hotkeys menu.
2. Assign hotkey with Shift modifier to any action. (I've assigned Shift-1 to open file with a tool).
3. Test if it works.

### Additional Information

Assigning Shift-{key} (or anything with Shift, can be Cmd-Shift too) assigns key to:
 **"Shift-!"** instead **"Shift-1",** 
**"Cmd-Shift-$"** instead **"Cmd-Shift-4"** etc.

 The result of this is not working shortcut. The problem is not how program interprets the keys but how it assigns it. Going to Config.json and changing **"shortcut": "⇧⌥#"** to **"shortcut": "⇧⌥3"** makes it work as expected.

**Comment by mikekazakov** [comment]
Using Shift as the only modifier is very error prone because it's sensitive to the keyboard layout, I'd recommend to avoid it. Though in my case assigning Shift+1 works as expected:
<img width="524" alt="Screenshot 2024-09-23 at 19 05 35" src="https://github.com/user-attachments/assets/aa248bde-d851-4398-a578-07a91ea62721">
<img width="286" alt="Screenshot 2024-09-23 at 19 06 33" src="https://github.com/user-attachments/assets/3c99fe91-4a12-45d2-abab-58d3bf749561">

More information about the context is needed.

**Comment by teropentis64** [comment]
Yeah I thought that may be too problematic to implement for various keyboard layouts. That may be a problem with my input layout. Thats not a big deal anyway as someone could easily change it themselves by going into Config.json file.

**Comment by mikekazakov** [comment]
Ok, I'll close this issue as it's not clear what the right thing should be.
