### ISSUE TITLE
"Connect to SFTP server" dialog is impossible to get through: password is invalid

### ISSUE THREAD

**Issue by singalen** [mikekazakov/nimble-commander#82]
I'm having a red warning sign near `password` field forever.
I'm selecting a public ssh key file with an empty password. 
No matter if I select public or private key file or what I type into a password, the red sign is there and "Connect" button is disabled.

**Comment by fatherofinvention** [comment]
@singalen I know this is a pretty old issue, but I had the same thing happen and it was because the passphrase I was entering for the **private** key file I had chosen was incorrect. Once I fixed it the red exclamation point icon went away and I was able to login successfully. 

I think this issue can probably be closed.

**Comment by yougotwill** [comment]
> I'm having a red warning sign near `password` field forever. I'm selecting a public ssh key file with an empty password. No matter if I select public or private key file or what I type into a password, the red sign is there and "Connect" button is disabled.

I made the same mistake but you have to use your private key for the key file. I think this issue can be closed
